apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: system
  source:
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 3.35.0
    chart: argo-cd
    helm:
      values: ""
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - "CreateNamespace=true"
