apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  project: system
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.0.17
    chart: ingress-nginx
    helm:
      values: |
        controller:
          updateStrategy:
            type: RollingUpdate
            rollingUpdate:
              maxUnavailable: 1
          hostPort:
            enabled: true
          terminationGracePeriodSeconds: 0
          service:
            type: NodePort
          watchIngressWithoutClass: true
          nodeSelector:
            ingress-ready: "true"
          tolerations:
            - key: "node-role.kubernetes.io/master"
              operator: "Equal"
              effect: "NoSchedule"
          publishService:
            enabled: false
          extraArgs:
            publish-status-address: localhost
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - "CreateNamespace=true"
