apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: system
  namespace: argocd
spec:
  description: System addons
  sourceRepos:
    - https://kubernetes.github.io/ingress-nginx
    - https://argoproj.github.io/argo-helm
    - https://cdfoundation.github.io/tekton-helm-chart/
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
